### PR TITLE
[SIS-41] Updating FAQ's UI, styling, design and questions

### PR DESCRIPTION
**Pull request by srujankarthik**
Completes [SIS-41](https://amlp.atlassian.net/browse/SIS-41)
Screenshot 2023-09-09 at 7 49 25 pm

### CODE REVIEW

**Comment by henrygoodman** [comment]
Reviews are back homies

**Comment by srujankarthik** [comment]
42crbn

**Review by henrygoodman — APPROVED** [review]
image

**Review by gracebilliris — APPROVED** [review]
The questions and answers look great!

**Review by stephenb-coding — APPROVED** [review]

**Pull request merged**
