### PR TITLE
WIP Fixing `NavBar` Bugs 🐛

### LINKED ISSUE #139: Bug(s): `NavBar` Element 🐛
Tasks:
- [ ] Removing _Learning Material Summary_ in the `Navbar`. Renaming _Questions_ to _Learn more_. Combining _Learning Material Summary_ and (old) _Questions_ content into the _Learn more_ page.

### PR DESCRIPTION
**Pull request by gracebilliris**
This PR includes the following tasks:
- [x] Combining `FAQ` & `LearningMaterialSummary` Pages
- [x] Adding NLP question and answer for the new `Learn More` page.
- [x] Removing the `LearningMaterialSummary` page
- [x] Updating Cypress Test for `Home` Page
- [x] Removing `LearningMaterialSummary` Cypress test
- [x] Removing `NavBar` Cypress test
- [x] Removing `About` Cypress test
- [x] Removing `FAQ` Cypress test
- [x] Removing `Text Font Customisation` Cypress test
- [x] Renaming `Summary and Emotion` Cypress tests
- [x] Establishing the foundation for `History` Cypress test
- [x] Updating `LearnMore` Cypress test for new UI
- [x] Adding `viewport` setting for Cypress window size for _About_ Page, _Summary Feature_, _SentimentAnalysis_, and _EmotionAnalysis_ tests.

### CODE REVIEW

**Comment by gracebilliris** [comment]
UI Option 1 (two distinct sections for FAQ and Learning Material Summary Questions): 
image

UI Option 2 (questions for both sections combined):
image

**Comment by gracebilliris** [comment]
> UI Option 1 (two distinct sections for FAQ and Learning Material Summary Questions): image
> 
> UI Option 2 (questions for both sections combined): image

Going with UI Option 1 after discord discussion:
image

**Comment by JamesBug404** [comment]
LGTM!

**Review by JamesBug404 — APPROVED** [review]
LGTM!

**Review by srujankarthik — APPROVED** [review]
nice, looks good

**Pull request merged**
