### PR TITLE
Home (Bug) Fixes

### LINKED ISSUE #170: Bug(s) 🐛 🐞 🐜
Image

- [ ] Clear _input button_ function for the _text to be summarised_

### PR DESCRIPTION
**Pull request by srujankarthik**
* Changed the "Text to be summarised" to "Text to be analysed"

### CODE REVIEW

**Comment by srujankarthik** [comment]
@JamesBug404 just added in a few more reviewers, sorry I wasn't able to type on discord cause it's buggy

**Comment by JamesBug404** [comment]
image

Fixed Change font display bug, emotion "Fear" colour.

**Comment by henrygoodman** [comment]
Small one I had in mind, the placeholder text for the Input Textarea mentions `Enter 100 words or more to summarise` (or something along those lines). 

Could this also be changed to `Enter 100 words or more to analyse`? TY

**Comment by JamesBug404** [comment]
> Enter 100 words or more to summarise

Done.

**Comment by henrygoodman** [comment]
> > Enter 100 words or more to summarise
> 
> Done.

That latest change only updated the div title, not the placeholder text
If you ctrl-f for `placeholder` it should show up

Also this change seemed to have caused some regression issues in the 1st Cypress test, which seems to check font options. One of you may have to update the strings in this test case

**Review by henrygoodman — APPROVED** [review]

**Comment by JamesBug404** [comment]
> > > Enter 100 words or more to summarise
> > 
> > 
> > Done.
> 
> That latest change only updated the div title, not the placeholder text If you ctrl-f for `placeholder` it should show up
> 
> Also this change seemed to have caused some regression issues in the 1st Cypress test, which seems to check font options. One of you may have to update the strings in this test case

oops, sorry my bad... :/

**Review by gracebilliris — APPROVED** [review]
Looks good!

**Review by stephenb-coding — APPROVED** [review]

**Comment by srujankarthik** [comment]
home bug fixes

**Pull request merged**
