### PR TITLE
Feature: Copy summarised text to clipboard

### LINKED ISSUE #140: Feature: Copy `Summarised Text` to Clipboard.

### PR DESCRIPTION
**Pull request by JamesBug404**
The copy text Button will be disabled until there is text in the summarised text box. After clicking the copy button, alert will pops up to notify the user.
image
image

### CODE REVIEW

**Review by gracebilliris — CHANGES_REQUESTED** [review]
@JamesBug404 Just tried testing this, the _copy text_ `button` works even when the _summary_ button hasn't been pressed. No text is copied to the keyboard at this point. 
image

However, once the _summary_ `button` is pressed, then text is copied to keyboard. I think we may need to add an extra condition to the _copy text_ `button` so only if the _summarised_ `button` has been pressed then the _copy text_ `button` can be pressed.
image

**Comment by JamesBug404** [comment]
> @JamesBug404 Just tried testing this, the _copy text_ `button` works even when the _summary_ button hasn't been pressed. No text is copied to the keyboard at this point. image
> 
> However, once the _summary_ `button` is pressed, then text is copied to keyboard. I think we may need to add an extra condition to the _copy text_ `button` so only if the _summarised_ `button` has been pressed then the _copy text_ `button` can be pressed. image

@gracebilliris Thanks for letting me know, the bug is now fixed.

**Review by gracebilliris — APPROVED** [review]
Looks good!

**Review by srujankarthik — APPROVED** [review]
looks good! nice work Roy

**Comment by henrygoodman** [comment]
@JamesBug404 

In my PR https://github.com/SIS-Team-24/2023-SIS-Team-24/pull/190

I had added a popup for when copying the URL to the clipboard, it is like a popup that shows up under the users mouse, with customizable text. I think it would be good to also use here instead of a browser alert, just so we have consistent interfaces.

For reference, it looks like this:

https://github.com/SIS-Team-24/2023-SIS-Team-24/assets/79623665/44ac9060-e401-4e6d-923a-2c4935f4bad6



If my PR was merged first, it would be simple to see how to use 😆 but for now, you can make following code changes in `Home.tsx`:

Add this global popup tracker at top of file (just makes sure there is only ever 1 popup so it doesnt clutter screen):
```
  let currentPopup: any = null;
```

Add this function to show the popup 
```
    const showMousePopup = (mouseX: Number, mouseY: Number, text: string) => {
    // If there's an existing popup, remove it
    if (currentPopup) {
      currentPopup.remove(); // Using the remove method, which is simpler and avoids the error.
      currentPopup = null; // Reset the currentPopup reference
    }

    // Create a new element for the popup
    const popup = document.createElement('div');
    popup.textContent = text;
    popup.style.position = 'absolute';
    popup.style.left = `${mouseX}px`;
    popup.style.top = `${mouseY}px`;
    popup.style.backgroundColor = '#000';
    popup.style.color = '#fff';
    popup.style.padding = '8px';
    popup.style.borderRadius = '4px';
    popup.style.zIndex = '1000';
    popup.style.transform = 'translate(-50%, 100%)';
    popup.style.transition = 'opacity 0.5s'; // Fade out animation
    document.body.appendChild(popup);

    // Store the current popup
    currentPopup = popup;

    // Fade out the popup after a delay and then remove it from the DOM
    setTimeout(() => {
        popup.style.opacity = '0';
        setTimeout(() => {
            if (popup.parentElement) {  // Ensure the popup still has a parent
                popup.remove();
            }
            if (popup === currentPopup) {
                currentPopup = null;
            }
        }, 500); // match the duration of the transition
    }, 1000);
  };
```

Call with this `onClick ={ (e) => showMousePopup(event.clientX, event.clientY, text) }` (text is a variable, set it to whatever you want the popup to say)

LMK if this makes sense, or just look at my PR code/ checkout if you wanna see how it works first

**Review by henrygoodman — DISMISSED** [review]
****

**Comment by JamesBug404** [comment]
> @JamesBug404
> 
> In my PR #190
> 
> I had added a popup for when copying the URL to the clipboard, it is like a popup that shows up under the users mouse, with customizable text. I think it would be good to also use here instead of a browser alert, just so we have consistent interfaces.
> 
> For reference, it looks like this:
> 
>  Text.Insights.-.Opera.2023-10-20.12-50-30.mp4 
> If my PR was merged first, it would be simple to see how to use 😆 but for now, you can make following code changes in `Home.tsx`:
> 
> Add this global popup tracker at top of file (just makes sure there is only ever 1 popup so it doesnt clutter screen):
> 
> ```
>   let currentPopup: any = null;
> ```
> 
> Add this function to show the popup
> 
> ```
>     const showMousePopup = (mouseX: Number, mouseY: Number, text: string) => {
>     // If there's an existing popup, remove it
>     if (currentPopup) {
>       currentPopup.remove(); // Using the remove method, which is simpler and avoids the error.
>       currentPopup = null; // Reset the currentPopup reference
>     }
> 
>     // Create a new element for the popup
>     const popup = document.createElement('div');
>     popup.textContent = text;
>     popup.style.position = 'absolute';
>     popup.style.left = `${mouseX}px`;
>     popup.style.top = `${mouseY}px`;
>     popup.style.backgroundColor = '#000';
>     popup.style.color = '#fff';
>     popup.style.padding = '8px';
>     popup.style.borderRadius = '4px';
>     popup.style.zIndex = '1000';
>     popup.style.transform = 'translate(-50%, 100%)';
>     popup.style.transition = 'opacity 0.5s'; // Fade out animation
>     document.body.appendChild(popup);
> 
>     // Store the current popup
>     currentPopup = popup;
> 
>     // Fade out the popup after a delay and then remove it from the DOM
>     setTimeout(() => {
>         popup.style.opacity = '0';
>         setTimeout(() => {
>             if (popup.parentElement) {  // Ensure the popup still has a parent
>                 popup.remove();
>             }
>             if (popup === currentPopup) {
>                 currentPopup = null;
>             }
>         }, 500); // match the duration of the transition
>     }, 1000);
>   };
> ```
> 
> Call with this `onClick ={ (e) => showMousePopup(event.clientX, event.clientY, text) }` (text is a variable, set it to whatever you want the popup to say)
> 
> LMK if this makes sense, or just look at my PR code/ checkout if you wanna see how it works first

image

@henrygoodman Thanks for sharing the code, I have made those changes and updated the notification message.

**Review by JamesBug404 — COMMENTED** [review]
code updated.

**Pull request merged**
