### PR TITLE
[SIS-114] store and display summary history

### LINKED ISSUE #81: US-14: As a developer, I want the system to be able to (temporarily) store outputted summaries, so they can be reviewed for testing.

### LINKED ISSUE #82: US-01: As a user, I want to view the text's summary history in the system, so that I can always go back to it.

### PR DESCRIPTION
**Pull request by stephenb-coding**
Solves [SIS-114](https://amlp.atlassian.net/browse/SIS-114)

Store summary items in the session storage and make them available for viewing on the Summary History page.

image
image
image

### CODE REVIEW

**Comment by henrygoodman** [comment]
This is awesome, LGTM

Just checking, it looks like this PR also makes it so the sentiment and summary executes based on the input of the text area instead of the hardcoded test strings?

**Review by henrygoodman — APPROVED** [review]

**Review by gracebilliris — APPROVED** [review]
Looks good!
Good to see the implemented summary history logic.

**Comment by gracebilliris** [comment]
I believe the previous PR (already merged into development) changed from hardcoded text to the input from the text area! 

> This is awesome, LGTM
> 
> Just checking, it looks like this PR also makes it so the sentiment and summary executes based on the input of the text area instead of the hardcoded test strings?

**Comment by stephenb-coding** [comment]
> This is awesome, LGTM
> 
> Just checking, it looks like this PR also makes it so the sentiment and summary executes based on the input of the text area instead of the hardcoded test strings?

Yes. `getSummary` and `getSentiment` now use `inputValue` instead of a hardcoded string. As @gracebilliris mentioned, it should have been changed to this at some point so I'm unsure why it was still hardcoded.

**Pull request merged**
