### PR TITLE
update navbar styling and font

### PR DESCRIPTION
**Pull request by srujankarthik**
Updated navbar styling to match open-sans font
Remove CSS to update with tailwind
Some additional styling, such as underline on hover

Screenshot 2023-09-18 at 5 21 26 pm

### CODE REVIEW

**Review by gracebilliris — APPROVED** [review]
New `NavBar` looks great!

**Comment by srujankarthik** [comment]
@gracebilliris would this be preferable instead of the other one? this one is a bit subdued

Screenshot 2023-09-18 at 5 35 20 pm

**Comment by gracebilliris** [comment]
> @gracebilliris would this be preferable instead of the other one? this one is a bit subdued
> 
> Screenshot 2023-09-18 at 5 35 20 pm

@srujankarthik What's the difference? the `hover:underline` styling is now gone?

**Comment by srujankarthik** [comment]
@gracebilliris just that the image is a bit smaller `300px` and the nav items are displayed in flex and spaced out with 10px each

**Comment by gracebilliris** [comment]
@srujankarthik can you make the logo slightly bigger? it's not as easy to see when it's almost the same height as the normal text.

**Comment by srujankarthik** [comment]
@gracebilliris 400px width, same styling as the first one which you approved
fyi the first one was 500px

Screenshot 2023-09-18 at 5 44 45 pm

**Comment by gracebilliris** [comment]
@srujankarthik yeah, it's a bit better. I don't suppose we could eliminate some of the left margin padding - to create more space between the logo and the `NavBar` tabs?

**Comment by srujankarthik** [comment]
Screenshot 2023-09-18 at 5 48 24 pm
is this better? @gracebilliris

**Comment by gracebilliris** [comment]
@srujankarthik I think so. What do you think?

**Review by henrygoodman — APPROVED** [review]

**Pull request merged**
