### PR TITLE
Srujan/us05 UI fixes

### LINKED ISSUE #97: US-05: As a user, I want the system to have an easy to use and simple, so that I can easily navigate the system.
Tasks:
- [ ] [Current Issue 128](https://github.com/SIS-Team-24/2023-SIS-Team-24/issues/128)
- [ ] [Current Issue 127](https://github.com/SIS-Team-24/2023-SIS-Team-24/issues/127)

### PR DESCRIPTION
**Pull request by srujankarthik**
* Overhauled Home UI

Screenshot 2023-10-14 at 12 54 34 pm
Screenshot 2023-10-14 at 12 55 57 pm

### CODE REVIEW

**Comment by srujankarthik** [comment]
@gracebilliris @Rgonzales4 okay so the important stuff of overhauling the text boxes and the font and summary changing is done, but I'd need to discuss where to put the Sentiment of the text is... and the other on the screen.

There's already so much we could do by overhauling it but how exactly would the other new features be put in, in the remaining space.

One solution for the sentiment might be to have it show up like the summary history view?

**Comment by srujankarthik** [comment]
@gracebilliris @Rgonzales4 
This is how it looks like
Screenshot 2023-10-15 at 11 16 39 am

**Comment by srujankarthik** [comment]
Screenshot 2023-10-15 at 12 41 36 pm
the favicon for the project @gracebilliris @Rgonzales4 @SSBdevelopment @henrygoodman @Kyrus2504 @JamesBug404

**Comment by henrygoodman** [comment]
> Screenshot 2023-10-15 at 12 41 36 pm the favicon for the project @gracebilliris @Rgonzales4 @SSBdevelopment @henrygoodman @Kyrus2504 @JamesBug404

how does this look? I thought favicons were traditionally 128x128 (or like kinda square shaped), but that one is a long rectangle. Unless you mean the speech bubble thing in the left is the icon, in which case I think looks good 👍

**Review by henrygoodman — APPROVED** [review]

**Comment by srujankarthik** [comment]
> > Screenshot 2023-10-15 at 12 41 36 pm the favicon for the project @gracebilliris @Rgonzales4 @SSBdevelopment @henrygoodman @Kyrus2504 @JamesBug404
> 
> how does this look? I thought favicons were traditionally 128x128 (or like kinda square shaped), but that one is a long rectangle. Unless you mean the speech bubble thing in the left is the icon, in which case I think looks good 👍

yeah it is the left text bubble icon

**Comment by JamesBug404** [comment]
> > > Screenshot 2023-10-15 at 12 41 36 pm the favicon for the project @gracebilliris @Rgonzales4 @SSBdevelopment @henrygoodman @Kyrus2504 @JamesBug404
> > 
> > 
> > how does this look? I thought favicons were traditionally 128x128 (or like kinda square shaped), but that one is a long rectangle. Unless you mean the speech bubble thing in the left is the icon, in which case I think looks good 👍
> 
> yeah it is the left text bubble icon

i think it looks good

**Comment by henrygoodman** [comment]
Awesome, I can see the icon now in the files. Just checking, I checked out this pr and ran `npm run dev`, however the icon didn't update and I am still seeing the React default icon. Is this the same for you? Or is there something specific we must do to see the icon update

**Comment by srujankarthik** [comment]
> Awesome, I can see the icon now in the files. Just checking, I checked out this pr and ran `npm run dev`, however the icon didn't update and I am still seeing the React default icon. Is this the same for you? Or is there something specific we must do to see the icon update

Can you try clearing your cache and running `npm run build:clean`

**Comment by henrygoodman** [comment]
> > Awesome, I can see the icon now in the files. Just checking, I checked out this pr and ran `npm run dev`, however the icon didn't update and I am still seeing the React default icon. Is this the same for you? Or is there something specific we must do to see the icon update
> 
> Can you try clearing your cache and running `npm run build:clean`

Clearing browser cache worked 👍 looks good

**Review by Rgonzales4 — APPROVED** [review]
LGTM king stuff right here 🐱

**Pull request merged**
